server:
  port: 8090
  context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cyber?zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=UTF-8&characterSetResults=UTF-8
    username: root
    password: 123456789
#  mvc:
#    view:
#      prefix: /WEB-INF/
#      suffix: .jsp
#  mail:
#    protocol: smtp #smtp是邮件发送协议，pop3和imap是邮件接收协议。因为我们要发送邮件，因此是smtp
#    host: smtp.163.com #邮件发送服务器的主机，这里采用的是126邮箱来发送邮件
#    port: 25 #邮件发送服务器的端口
#    auth: true #一般情况下，发送邮件都是要进行验证
#    username: fanjianan916@163.com #邮件发送服务器的用户名
#    password: fanjianan1110 #密码
#  data:
#    mongodb:
#      host: 127.0.0.1
#      port: 27017
#      database: mo
#  http:
#    multipart:
#      enabled: true
#      max-file-size: 9MB
#      max-request-size: 9MB
#mybatis:
#  config-location: classpath:/mybatis/mybatis-config.xml
#  mapper-locations: classpath:/mybatis/mappers/*.xml
#  type-aliases-package: xin.mo.pojo
##分页助手
#pagehelper:
#  helperDialect: mysql
#  reasonable: false
#  supportMethodsArguments: true
#  params: count=countSql
#  row-bounds-with-count: true
#  offset-as-page-num: true